# Generated by Django 6.0.7 on 2026-07-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_slug', models.SlugField(max_length=200, unique=True)),
                ('category_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_title', models.CharField()),
                ('collection_description', models.TextField(blank=True)),
                ('collection_banner', models.ImageField(upload_to='collections/')),
                ('collection_cover', models.CharField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField()),
                ('p_slug', models.SlugField()),
                ('p_description', models.TextField(blank=True)),
                ('p_price', models.FloatField()),
                ('p_sku', models.CharField(blank=True)),
                ('p_brand', models.TextField(blank=True)),
                ('p_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('p_collection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
            ],
        ),
    ]
