# Generated by Django 6.0.7 on 2026-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
