# Generated by Django 6.0.7 on 2026-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_p_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendercollection',
            name='title',
            field=models.CharField(blank=True, choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=100, null=True),
        ),
    ]
