# Generated by Django 6.0.7 on 2026-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_gendercollection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoe', 'Shoe'), ('general', 'General')], default='clothing', max_length=20),
        ),
    ]
