# Generated by Django 6.0.7 on 2026-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendercollection',
            name='title',
            field=models.CharField(blank=True, choices=[('womencollection', 'Women_Collection'), ('mencollection', 'Men_Collection'), ('kidscollection', 'Kids_Collection')], max_length=100, null=True),
        ),
    ]
